const FETCH_REQUEST = "FETCH_REQUEST"
const FETCH_SUCCESS = "FETCH_SUCCESS"
const FETCH_FAILURE = "FETCH_FAILURE"

const BOOK_DELETED_FROM_CART = "BOOK_DELETED_FROM_CART"
const BOOK_ADDED_TO_CART = "BOOK_ADDED_TO_CART"
const BOOK_DECREASED_FROM_CART = "BOOK_DECREASED_FROM_CART"
const BOOK_ADDED_TO_CART_FROM_SERVER = "BOOK_ADDED_TO_CART_FROM_SERVER"
const CART_RESET = "CART_RESET"

const EMAIL_UPDATE = "EMAIL_UPDATE"
const PASSWORD_UPDATE = "PASSWORD_UPDATE"
const FETCH_LOGIN_DATA = 'FETCH_LOGIN_DATA'
const FETCH_REGISTER_DATA = "FETCH_REGISTER_DATA"
const SET_TOKEN = "SET_TOKEN"
const LOGOUT = "LOGOUT"

const FETCH_BOOK_CREATED = "FETCH_BOOK_CREATED"
const FETCH_BOOKS = "FETCH_BOOKS"
const TITLE_UPDATE = "TITLE_UPDATE"
const AUTHOR_UPDATE = "AUTHOR_UPDATE"
const PRICE_UPDATE = "PRICE_UPDATE"
const COVER_IMAGE_UPDATE = "COVER_IMAGE_UPDATE"

const FETCH_ORDERS = "FETCH_ORDERS"


export {
    FETCH_REQUEST,
    FETCH_SUCCESS,
    FETCH_FAILURE,
    
    BOOK_DELETED_FROM_CART,
    BOOK_ADDED_TO_CART,
    BOOK_DECREASED_FROM_CART,
    BOOK_ADDED_TO_CART_FROM_SERVER,
    CART_RESET,
    
    EMAIL_UPDATE,
    PASSWORD_UPDATE,
    FETCH_LOGIN_DATA,
    FETCH_REGISTER_DATA,
    SET_TOKEN,
    LOGOUT,
    
    FETCH_BOOK_CREATED,
    FETCH_BOOKS,  
    TITLE_UPDATE,
    AUTHOR_UPDATE,
    PRICE_UPDATE,
    COVER_IMAGE_UPDATE,

    FETCH_ORDERS
}